const data = {
  status: "success",
  items: [
    {
      id: 1,
      title: "Desmoldante de color",
      price: 1200,
      image: "https://blendergroup.com/wp-content/uploads/2019/07/desmoldante-Blender.jpg",
      category: "Desmoldantes",
      img1: "https://blendergroup.com/wp-content/uploads/2019/07/desmoldante-Blender.jpg",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
      cantidad: 1,
    },

    {
      id: 2,
      title: "Moldes",
      price: 150,
      image: "https://blendergroup.com/wp-content/uploads/2019/07/Blender-Home-servicios-moldes.jpg",
      category: "Moldes",
      img1: "https://blendergroup.com/wp-content/uploads/2019/07/Blender-Home-servicios-moldes.jpg",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
      cantidad: 1,
    },
    {
      id: 3,
      title: "Recover W",
      price: 1350,
      image: "https://blendergroup.com/wp-content/uploads/2019/07/blender-group-concrete-overlays-recover.png",
      category: "Concreto Estampado",
      img1: "https://blendergroup.com/wp-content/uploads/2019/07/blender-group-concrete-overlays-recover.png",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
      cantidad: 1,
    },
    {
      id: 4,
      title: "Natural Stain",
      price: 1400,
      image: "https://blendergroup.com/wp-content/uploads/2019/08/blender-group-concreto-oxidado-natural-stain-1.png",
      category: "Oxidantes",
      img1: "https://blendergroup.com/wp-content/uploads/2019/08/blender-group-concreto-oxidado-natural-stain-1.png ",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
      cantidad: 1,
    },
    {
      id: 1,
      title: "Desmoldante de color",
      price: 1200,
      image: "https://blendergroup.com/wp-content/uploads/2019/07/desmoldante-Blender.jpg",
      category: "Desmoldantes",
      img1: "https://blendergroup.com/wp-content/uploads/2019/07/desmoldante-Blender.jpg",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
      cantidad: 1,
    },

    {
      id: 2,
      title: "Moldes",
      price: 150,
      image: "https://blendergroup.com/wp-content/uploads/2019/07/Blender-Home-servicios-moldes.jpg",
      category: "Moldes",
      img1: "https://blendergroup.com/wp-content/uploads/2019/07/Blender-Home-servicios-moldes.jpg",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
      cantidad: 10,
    },
    {
      id: 3,
      title: "Recover W",
      price: 1350,
      image: "https://blendergroup.com/wp-content/uploads/2019/07/blender-group-concrete-overlays-recover.png",
      category: "Concreto Estampado",
      img1: "https://blendergroup.com/wp-content/uploads/2019/07/blender-group-concrete-overlays-recover.png",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
      cantidad: 1,
    },
    {
      id: 4,
      title: "Natural Stain",
      price: 1400,
      image: "https://blendergroup.com/wp-content/uploads/2019/08/blender-group-concreto-oxidado-natural-stain-1.png",
      category: "Oxidantes",
      img1: "https://blendergroup.com/wp-content/uploads/2019/08/blender-group-concreto-oxidado-natural-stain-1.png ",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
      cantidad: 1,
    },
    {
      id: 1,
      title: "Desmoldante de color",
      price: 1200,
      image: "https://blendergroup.com/wp-content/uploads/2019/07/desmoldante-Blender.jpg",
      category: "Desmoldantes",
      img1: "https://blendergroup.com/wp-content/uploads/2019/07/desmoldante-Blender.jpg",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
      cantidad: 1,
    },

    {
      id: 2,
      title: "Moldes",
      price: 150,
      image: "https://blendergroup.com/wp-content/uploads/2019/07/Blender-Home-servicios-moldes.jpg",
      category: "Moldes",
      img1: "https://blendergroup.com/wp-content/uploads/2019/07/Blender-Home-servicios-moldes.jpg",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
      cantidad: 10,
    },
    {
      id: 3,
      title: "Recover W",
      price: 1350,
      image: "https://blendergroup.com/wp-content/uploads/2019/07/blender-group-concrete-overlays-recover.png",
      category: "Concreto Estampado",
      img1: "https://blendergroup.com/wp-content/uploads/2019/07/blender-group-concrete-overlays-recover.png",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
      cantidad: 1,
    },
    {
      id: 4,
      title: "Natural Stain",
      price: 1400,
      image: "https://blendergroup.com/wp-content/uploads/2019/08/blender-group-concreto-oxidado-natural-stain-1.png",
      category: "Oxidantes",
      img1: "https://blendergroup.com/wp-content/uploads/2019/08/blender-group-concreto-oxidado-natural-stain-1.png ",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
      cantidad: 1,
    }
   
  ],
};

export default data;